#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK
VERSION = 1.3

import argcomplete

import argparse

import logging

# sort files s1.pnm, ..., s9.pnm, s10.pnm, ...
from natsort import natsorted

# file path normalization and os.getcwd()
import os

from pathlib import Path

# provides copy command in case of skip_ocr
# needed to investigate PATH (check_command_exists)
import shutil

import subprocess

# provides sys.exit in case of errors
import sys

# Create tmp folder to work in and create unique non-existing file names
import tempfile

#################### CONFIG ####################

# See `scanimage --list-devices`
SCANNER = 'fujitsu:fi-6110dj:1206658'

# presets must use the long form flags (e.g. "resolution", not "r")
PRESETS = {
    "text": {
        "color": "gray",
        "resolution": 400,
        "nsparams": [
            '--skip_empty',
            '--white_background',
            '--binarize',
            '--normalize',
            '--denoise_opening',
            '--opening_strength', '1',
            '--unsharp_mask',
            '--unsharp_amount', '5',
            '--unsharp_radius', '15',
            ],
        },

    "ctext": {
        "color": 'color',
        "resolution": 400,
        "nsparams": [
            '--skip_empty',
            '--white_background',
            '--black',
            '--normalize',
            '--n_colors', '10',
            '--denoise_opening',
            '--opening_strength', '1',
            '--unsharp_mask',
            '--unsharp_amount', '1',
            '--unsharp_radius', '1',
            ],
        },

    "smusic": {
        "color": "gray",
        "resolution": 400,
        "nsparams": [
            '--skip_empty',
            '--white_background',
            '--binarize',
            '--normalize',
            '--denoise_opening',
            '--opening_strength', '1.9',
            '--unsharp_mask',
            '--unsharp_amount', '5',
            '--unsharp_radius', '15',
            ],
        },
    }

################################################

# Convert PRESETS[key] to string
# Helper function to generate strings for the --preset help text.
presets2string = lambda key: " ".join([f"--{k} {v}" if not isinstance(v, list) else f'--{k} "{" ".join(v)}"' for k,v in PRESETS[key].items()])

def parse_args():
    """
    Parses command line arguments.

    Returns:
        argparse.Namespace: A namespace that holds the arguments as attributes.
    """

    parser = argparse.ArgumentParser(
        description="Scan a document and save it as an optimized, OCRed and tagged PDF.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument(
        "output_file",
        default='output.pdf',
        nargs='?',
        type=Path,
        help="Output File Name for the Scanned Document")

    parser.add_argument(
        "-m",
        "--mode",
        help="Single sided / duplex scanning. The side facing away from the user is the <single> page / the first page of the <duplex> mode.",
        choices=[
            "single",
            "duplex"],
        default="duplex",
        type=str.lower)
    parser.add_argument(
        "-c",
        "--color",
        help="Color Mode: Lineart / Gray / Color",
        choices=[
            "lineart",
            "gray",
            "color"],
        default="color",
        type=str.lower)
    parser.add_argument(
        "-p",
        "--preset",
        help='Presets:'
            +f'"text":  A preset for text that results in black-and-white scans - corresponds to \'{presets2string("text")}\','
            +f'"ctext": A preset for text scans including colors - corresponds to \'{presets2string("ctext")}\','
            +f'"smusic": A preset for sheet music scans - corresponds to \'{presets2string("smusic")}\'',
        choices=[
            "text",
            "ctext",
            "smusic",
            ],
        default='',
        type=str.lower)
    parser.add_argument(
        "-r",
        "--resolution",
        help="Scanning Resolution",
        choices=range(
            50,
            601),
        metavar="{50..600}",
        default=300,
        type=int)
    parser.add_argument(
        '-t',
        '--tags',
        help="Comma-separated list of tags to be used with tmsu.\nE.g. \"tag1, tag2, tag3\"",
        type=lambda t: [s.strip() for s in t.strip().split(',')],
        default=None)
    parser.add_argument(
        "-s",
        "--paper-size",
        help="Paper Size for Scanning",
        choices=["a4", "a5"],
        default="a4",
        type=str.lower)
    parser.add_argument(
        "--text",
        action='store_true',
        default=False,
        help=f'Short for --preset="text" - A preset for text that results in black-and-white scans - corresponds to \'{presets2string("text")}\'')
    parser.add_argument(
        '--scan',
        action='store_true',
        default=False,
        help='Just scan to images, skip the rest.')
    parser.add_argument(
        '-k',
        '--keep_intermediate',
        action='store_true',
        default=False,
        help='Do not delete intermediate scans afterwards.')
    parser.add_argument(
        '--nsparams',
        help="Arguments to be used for noteshrunk (see noteshrunk -h).",
        type=lambda t: [s.strip() for s in t.strip().split(' ')],
        default='-w -s --unsharp_mask')
    parser.add_argument(
        "--skip-ocr",
        help="Skip OCR on the scanned document.",
        action="store_true",
        default=False)
    parser.add_argument(
        "-l",
        "--language",
        action='append',
        help="Tesseract OCR language: eng, deu, spa, fra, ita, ... Can be used multiple times for multiple languages. See `tesseract --list-langs` for installed languages or here for further information: https://ocrmypdf.readthedocs.io/en/latest/languages.html",
        default=['eng', 'deu'])
    parser.add_argument(
        '-d',
        '--deskew',
        action='store_true',
        default=False,
        help='Pass the --deskew flag to ocrmypdf for automatic deskewing.')
    parser.add_argument(
        '-v',
        '--verbose',
        action='count',
        help="Increase verbosity. Use twice to activate flushing of subprocess stdout to terminal.",
        default=0)
    parser.add_argument(
        '-y',
        '--overwrite',
        action='store_true',
        default=False,
        help='Answer all questions with Yes. Overwrite existing files / Create TMSU database without asking.')
    parser.add_argument(
        '--version',
        action='version',
        version=VERSION,
        help='Show program version and exit')

    argcomplete.autocomplete(parser)

    return parser, parser.parse_args()

def check_if_tmsu_db_exists(args):
    """
    Checks if a TMSU database exists in the current directory.

    Args:
        args (argparse.Namespace): The command line arguments.

    Returns:
        bool: True if a TMSU database exists, False otherwise.
    """

    # Try to list the tags. If this succeeds the db exists, otherwise not.
    # This is tied to the parsing speed of the db but _should_ be fast.
    # Collect the output to not flush them to stdout
    return_code = run_command(args, ['tmsu', 'tags'], capture_output=True, returncode_accept=1)

    return True if return_code == 0 else False

def run_command(args, command, capture_output=False, returncode_accept=None):
    """
    Runs a command as a subprocess and handles potential errors.

    Args:
        args (argparse.Namespace): The command line arguments.
        command (list): The command to be executed as a list of strings.
        capture_output (bool, optional): Whether to capture the command's output.
        returncode_accept (int, optional): An expected return code that indicates success.

    Returns:
        return code (int): The return / exit code of the command. 0 if the command executed successfully,
                           <returncode_accept> if it failed with the accepted return code.
    """
    assert isinstance(command, list)

    try:
        command = [ c.strip() for c in command if c.strip() != '' ]
        logging.debug('Running command \'{}\''.format(' '.join(command)))
        subprocess.run(command, capture_output=False if args.verbose >= 2 else capture_output, check=True)
        return 0

    except subprocess.CalledProcessError as e:

        if e.returncode != returncode_accept:

            logging.critical(e.stderr.decode('utf-8') if e.stderr is not None else None)
            logging.critical("Stdout was: " + str(e.stdout.decode('utf-8') if e.stdout is not None else None))
            sys.exit(1)
        else:
            return e.returncode

    except FileNotFoundError:
        logging.critical("Error: {} is not installed or not found in PATH.".format(command[0]))
        sys.exit(1)

    except Exception as e:
        logging.critical(f"An unexpected error occurred: {e}")
        sys.exit(1)

def scan_document(args, paper_size, resolution, mode, color, folder='./'):
    """
    Scans a document using scanimage and saves it as PNM images in the specified folder.

    Args:
        args (argparse.Namespace): The command line arguments.
        paper_size (str): The paper size, such as "a4" or "a5".
        resolution (int): The scanning resolution in DPI.
        mode (str): The scanning mode, either "single" or "duplex".
        color (str): The color mode, either "lineart", "gray", or "color".
        folder (str, optional): The folder to save the scanned images. Defaults to './'.
    """

    logging.info('Scanning to {} ...'.format(folder))

    # Execute the scanning command
    run_command(args, [
        "scanimage",
        "-d", SCANNER,
        "--verbose" if args.verbose else '',
        "--progress",
        "--resolution", str(resolution),
        "--source", "ADF Duplex" if mode == "duplex" else "ADF Front",
        "--batch-count=999", "--batch=" + str(Path(folder).joinpath("s%d.pnm")), "--batch-start=1",
        "--buffermode", "On",
        "--page-width", "210" if paper_size == "a4" else (
            "148" if paper_size == "a5" else (
            "105" if paper_size == "a6" else "210")),
        "--page-height", "297" if paper_size == "a4" else (
            "210" if paper_size == "a5" else (
            "148" if paper_size == "a6" else "297")),
        "-y", "297" if paper_size == "a4" else (
              "210" if paper_size == "a5" else (
              "148" if paper_size == "a6" else "297")),
        "--ald=yes",
        "--mode", color.capitalize(),
        "--format", "pnm",
        "--emphasis", "50",  # Sharpen image (-128..127)
        "--brightness", "20",  # (-127..127)
    ],
        capture_output=True,
        returncode_accept=7,
    )
    logging.info("Done")

def compress_document(args, folder='./'):
    """
    Compresses scanned PNM images in the specified folder into a PDF file using noteshrunk.
    Expects implicite name convention s%d.pnm within folder "folder"

    Args:
        args (argparse.Namespace): The command line arguments.
        folder (str, optional): The folder containing the PNM images. Defaults to './'.

    Returns:
        pathlib.Path: The path to the compressed PDF file.
    """

    # Create unique temp file and fetch it's name
    # This will be the temp pdf file name
    file_pdf = tempfile.NamedTemporaryFile(dir=Path(folder)).name
    file_pdf = Path(file_pdf).with_suffix('.pdf')

    # Execute the compression command
    logging.info('Compressing images ...')
    run_command(args, ["noteshrunk-dev"] + ['--dpi={}'.format(args.resolution)] + args.nsparams
        + args.verbose * ["--verbose"] + [
        "-o", str(file_pdf),
        *natsorted([str(x) for x in Path(folder).glob('s*.pnm') if x.is_file()], key=str),
    ],
        capture_output=True,
    )
    logging.info("Done")

    return file_pdf

def ocr_document(file, output_file, args):
    """
    Performs OCR on a PDF document using ocrmypdf and saves the result to a new file.

    Args:
        file (pathlib.Path): The path to the input PDF file.
        output_file (pathlib.Path): The path to save the OCRed PDF file.
        args (argparse.Namespace): The command line arguments.
    """
    # Execute the compression command
    logging.info('OCRing document {} ...'.format(file))
    run_command(args, [
        'ocrmypdf',
        '-v' if args.verbose >= 1 else '',
        '-l', '+'.join(list(set(args.language))),
        '--deskew' if args.deskew else '',
        str(file),
        '{}'.format(str(output_file))
    ],
        capture_output=True,
    )
    logging.info('Done')

def check_command_exists(command_name: str):
    """
    Checks if a given command exists in the system's PATH.

    Args:
        command_name (str): The name of the command to check.

    Returns:
        bool: True if the command is found in the PATH, False otherwise.
    """
    if not (shutil.which(command_name) is not None):
        raise RuntimeError('"{}" not found in PATH! Is it installed?'.format(command_name))

def overwrite_ifnotdefault(param, value, parser, args):
    """
    Overwrite <args>.nsparams with a list of given <params>.

    Args:
        nsparams (list): The command to be executed as a list of strings.
        args (argparse.Namespace): The command line arguments.

    Returns:
        args (argparse.Namespace): The command line arguments.
    """
    if param.startswith('--'):
        pass
    elif param.startswith('-'):
        pass
    else:
        pass
    default = [s.strip() for s in parser.get_default('nsparams').strip().split(' ')]

    # If custom commands are given, they take precedence.
    if nsparams != default:
        pass

def main():
    parser, args = parse_args()

    #print(parser.get_default('--nsparams'))
    #sys.exit(0)
    if args.verbose == 1:
        logging.basicConfig(encoding='utf-8', format="%(levelname)s:%(message)s", level=logging.INFO)
    elif args.verbose == 2:
        logging.basicConfig(encoding='utf-8', format="%(lineno)d-%(levelname)s:%(message)s", level=logging.WARNING)
    else:
        logging.basicConfig(encoding='utf-8', format="%(lineno)d-%(levelname)s:%(message)s", level=logging.DEBUG)

    # Check if external programs are accessible
    check_command_exists('scanimage')

    if args.tags is not None:
        check_command_exists('tmsu')

    if not args.skip_ocr:
        check_command_exists('ocrmypdf')
    
    if args.text:
        args.preset = "text"

    # Check if the application of a preset was ordered
    if args.text or ("-p" in sys.argv or "--preset" in sys.argv):

        # Find the parser actions defined in PRESETS[args.preset], e.g. PRESETS['text']
        for action in parser._actions:
            if action.dest in PRESETS[args.preset]:
                # action.option_strings contains the list of flags (e.g., ['-c', '--color'])
                # Apply preset option only if there is no override
                # (additional flags override preset settings)
                if not any(flag in sys.argv for flag in action.option_strings):
                    setattr(args, action.dest, PRESETS[args.preset][action.dest])

    if args.scan:
        args.keep_intermediate = True

    # Create tmp. folder within current folder
    # Reason: scanimage creates separate images files for each page. By
    # putting them into a separate folder, they can be deleted with the
    # termination of this folder.
    with tempfile.TemporaryDirectory(dir=os.getcwd(), prefix='tmp_scans-', delete=(not args.keep_intermediate)) as tmp_dir:

        # Temp. folder to save scans to
        tmp_dir = Path(tmp_dir)
        logging.debug('Temp. folder {} created.'.format(tmp_dir))

        if not args.scan:
            # Ensure output file is a pdf and sanitize path
            args.output_file = Path(os.path.normpath(args.output_file)).with_suffix('.pdf')
            logging.info('Setting {} as output file.'.format(args.output_file))

            # If output file exists, ask if overwrite.
            if args.output_file.exists():

                if args.overwrite:
                    logging.info('Overwriting existing file {} ...'.format(args.output_file))

                else:
                    while True:
                        response = input(
                            "File {} exists! Overwrite? [y/N] ".format(args.output_file)).strip().lower()
                        if response == '' or response == 'n':
                            logging.info("Exiting ...")
                            sys.exit(0)
                        elif response == 'y':
                            break

            # .absolute() method ensures that also locally referenced files are moved out of the temp. folder.
            # E.g. "test.pdf" --> "/my/path/to/test.pdf"
            args.output_file = args.output_file.absolute()

        # Save current location for later switching back
        folder_wd = os.getcwd()

        # You could also set the output destination of scanimage to the tmp_folder and work "from outside",
        # but it was easier to move and work from inside and just move the resulting pdf out in the end.

        # Move into temp. folder
        os.chdir(tmp_dir)

        scan_document(
            args=args,
            paper_size=args.paper_size,
            resolution=args.resolution,
            mode=args.mode,
            color=args.color,
            folder=os.getcwd(),
        )

        if not args.scan:
            # shrink pdf
            file_compressed = compress_document(args)

            if not args.skip_ocr:
                # OCR and save it to original folder ..
                ocr_document(
                    file=file_compressed,
                    output_file=args.output_file,
                    args=args,
                )
            else:
                # .. otherwise copy it to original folder
                shutil.copy(file_compressed, args.output_file)

            logging.info("Scanned to: {}".format(args.output_file))

        if args.keep_intermediate:
            logging.info(('Skipping the deletion of intermediate scans (folder {}).' if not args.scan
                          else 'Documents scanned to folder {}.').format(tmp_dir))

        # Move back to original folder (outside of temp. dir)
        os.chdir(folder_wd)

    # Tag resulting pdf if tags are given
    if args.tags is not None and not args.scan:

        # check if TMSU db exists
        if not check_if_tmsu_db_exists(args):

            if not args.overwrite:
                # If no TMSU db exists, ask if one should be created
                while True:
                    response = input(
                        "No TMSU db in the output folder! Create? [y/N] ").strip().lower()
                    if response == '' or response == 'n':
                        # If not, we're done.
                        logging.info("Exiting ...")
                        sys.exit(0)
                    elif response == 'y':
                        run_command(args, ['tmsu', 'init'], capture_output=True)
                        break
            else:
                run_command(args, ['tmsu', 'init'], capture_output=True)

        run_command(args, ['tmsu', 'tag', str(args.output_file)] + args.tags)
        logging.info('{} tagged with: '.format(args.output_file) + ', '.join(args.tags))


if __name__ == "__main__":
    main()
